<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Contact Form Submission </title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
            text-align: center;
        }
        .container {
            max-width: 600px;
            background: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin: auto;
            text-align: left;
        }
        h2 {
            color: #333;
            font-size: 22px;
            font-weight: bold;
            text-align: center;
            margin-top: 10px;
            padding-bottom: 8px;
            border-bottom: 2px solid #F45353;
            display: inline-block;
            width: 100%;
        }
        p {
            font-size: 14px;
            color: #555;
            line-height: 1.6;
        }
        .highlight {
            font-weight: bold;
            color: #F45353;
        }
        .footer {
            margin-top: 20px;
            font-size: 12px;
            color: #777;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .logo {
            max-width: 150px;
            display: block;
            margin: 0 auto 10px auto;
        }
    </style>
</head>
<body>
    <div class="container">

        <h2>New Contact Form Submission!</h2>

        <p>Hey metri team,</p>
        <p>Someone just reached out via the contact form. Here are the details:</p>

        <p><span class="highlight"> Name:</span> {{ e($data['name'] ?? 'N/A') }}</p>
        <p><span class="highlight">Email:</span> {{ e($data['email'] ?? 'N/A') }}</p>
        <p>
            <span class="highlight">Phone:</span> 
            @if(!empty($data['phone']))
                <a href="tel:{{ e($data['phone']) }}" style="color: #007bff; text-decoration: none;">
                    {{ e($data['phone']) }}
                </a>
            @else
                N/A
            @endif
        </p>      
        <p><span class="highlight">Message:</span> {{ e($data['message'] ?? 'N/A') }}</p>
        <div class="services-container">
            <p><span class="highlight">Services Requested:</span></p>
            @if(isset($data['services']) && is_array($data['services']) && count($data['services']) > 0)
                <ul>
                    @foreach($data['services'] as $service)
                        <li>{{ e($service) }}</li>
                    @endforeach
                </ul>
            @else
                <p>None</p>
            @endif  
        </div>
        <p>Let's get back to them as soon as possible!</p>

        <div class="footer">
            <p>This email was automatically generated by metri.id's contact system.</p>
        </div>
    </div>
</body>
</html>
